import type { Metadata } from "next";
import "./globals.css";
import localFont  from 'next/font/local';


const poppins=localFont({
  src:[
    {
      path:'../public/fonts/Poppins-Regular.ttf',
      weight:'400',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins-Bold.ttf',
      weight:'700',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins-Italic.ttf',
      weight:'400',
      style:'italic'
    },
    {
      path:'../public/fonts/Poppins-BoldItalic.ttf',
      weight:'700',
      style:'italic'
    },
    
  ],
  variable:'--font-poppins'
})

export const metadata: Metadata = {
  title: "Afriq-Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
